FROM databricksruntime/standard:13.3-LTS

RUN /databricks/python3/bin/pip install \
   configparser==6.0.0 \
   six==1.16.0 \
   jedi==0.18.1 \
   # ensure minimum ipython version for Python autocomplete with jedi 0.17.x
   ipython==8.10.0 \
   numpy==1.21.5 \
   pandas==1.4.4 \
   pyarrow==8.0.0 \
   matplotlib==3.5.2 \
   jinja2==2.11.3 \
   ipykernel==6.17.1 \
   grpcio==1.48.1 \
   grpcio-status==1.48.1 \
   databricks-sdk==0.1.6 \
   Keras==2.11.0 \
   Keras-Preprocessing==1.1.2 \
   tensorflow==2.11.0 \
   keras_tuner==1.4.0 \
   boto3==1.23.10 \
   statsmodels==0.14.0 \
   tqdm==4.62.3 \
   glob2==0.7 \
   pytz==2021.1 \
   scikit-learn==1.2.1